server {
    listen 80;
    listen [::]:80;
    server_name zedstaging.cloud www.zedstaging.cloud;

    # Folder untuk verifikasi Let's Encrypt otomatis
    location /.well-known/acme-challenge/ {
        root /var/www/html/public;
    }

    # Redirect semua traffic HTTP biasa ke HTTPS aman
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name zedstaging.cloud www.zedstaging.cloud;

    index index.php index.html;
    root /var/www/html/public;
    charset utf-8;

    # Lokasi sertifikat SSL di dalam container Nginx
    ssl_certificate /etc/letsencrypt/live/zedstaging.cloud/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/zedstaging.cloud/privkey.pem;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}